checks:
  php:
    code_rating: true
    duplication: true

  javascript:
    code_rating: true
    duplicate_code: true
filter:
  excluded_paths:
    - tests/*
    - js/dist/*
build:
  tests:
    override:
      - eslint-run js
tools:
  php_code_sniffer:
    config:
      standard: PSR2
