language: php 
php: 
 - 5.4

env:
  matrix:
   - DB=MYSQL CORE_RELEASE=3.1
   - DB=MYSQL CORE_RELEASE=3.4
   - DB=MYSQL CORE_RELEASE=master
   - DB=PGSQL CORE_RELEASE=master

matrix:
  include:
    - php: 5.6
      env: DB=MYSQL CORE_RELEASE=master

before_script:
 - phpenv rehash
 - composer self-update
 - git clone git://github.com/silverstripe-labs/silverstripe-travis-support.git ~/travis-support
 - php ~/travis-support/travis_setup.php --source `pwd` --target ~/builds/ss
 - cd ~/builds/ss

script: 
 - vendor/bin/phpunit switchflit/tests/
